# Generated by Django 3.1.13 on 2022-03-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_cases_officers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
